# Generated by Django 5.1.6 on 2025-02-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
