# Generated by Django 5.1.6 on 2025-02-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_cv_extracted_text_certification_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='company',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='position',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
