# Generated by Django 5.1.6 on 2025-02-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_workexperience_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='institution',
            new_name='issuer',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='year',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
