# Generated by Django 5.1.6 on 2025-02-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_rename_institution_certification_issuer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
