# Generated by Django 5.1.6 on 2025-03-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_workexperience_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='cv',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
