# Generated by Django 5.2.8 on 2025-12-03 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_education_cv_remove_personalinfo_cv_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'CV', 'verbose_name_plural': 'CVs'},
        ),
        migrations.AddField(
            model_name='cv',
            name='file_size',
            field=models.IntegerField(help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cv',
            name='original_filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CVSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('years_experience', models.FloatField(blank=True, null=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='documents.cv')),
            ],
            options={
                'verbose_name': 'CV Summary',
                'verbose_name_plural': 'CV Summaries',
            },
        ),
    ]
