# Generated by Django 5.2.8 on 2025-12-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_cv_options_cv_file_size_cv_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsummary',
            name='emails',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
