# Generated by Django 5.2.8 on 2025-12-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_cvsummary_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='file_hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
